### ISSUE TITLE
Argument of type 'string[]' is not assignable to parameter of type 'never[]'.

### ISSUE THREAD

**Issue by Czarnuszy** [greenpress/vuex-composition-helpers#11]
Hi there,
I'm trying to use this library in my project based on VueCompositionAPI & TypeScript and I've encountered this Type Error(screen attached below). It's not only with useActions, but with all functions extracted from `createNapespacedHelpers`. The weird thing is that all of those functions work as expected but my TS compiler keeps screaming at me 😢 

<img width="667" alt="Zrzut ekranu 2020-05-12 o 21 58 04" src="https://user-images.githubusercontent.com/17962053/81739628-f5a08180-949b-11ea-85cf-32b8e96df423.png">

**Comment by davidmeirlevy** [comment]
Hi,

Can you share an example of your code?
Can be a gist or any sample that you like.

Thanks.

**Comment by Tumselass** [comment]
Hi, 

I ran into the same issue. Created a sandbox where you also get the same type error.
Maybe we are doing something wrong?

https://codesandbox.io/s/adoring-kirch-7hqgw?file=/pages/index.vue

**Comment by davidmeirlevy** [comment]
@Tumselass @Czarnuszy The client is never wrong :)
You did everything as expected, and you found a great bug.

Fixed and now working on version 1.0.17.

Enjoy :)

**Comment by mokone91** [comment]
Hi! have same issue on 1.0.22(
