### ISSUE TITLE
Actions always return a promise

### ISSUE THREAD

**Issue by DotCoyote** [greenpress/vuex-composition-helpers#12]
It seems that `useActions` in combination with `createNamespacedHelpers` always creates asynchronous functions. I'm not 100% percent sure though, but this is our code (simplified):

Vue-Component:

```typescript
import {
  defineComponent, reactive, onMounted,
} from '@vue/composition-api';
import { createNamespacedHelpers } from 'vuex-composition-helpers';

const { useActions } = createNamespacedHelpers('authModule');

export default defineComponent({
  setup() {
    const localState = reactive({
      hasEthereum: false,
    });

    const { isEthereumPresent } = useActions(['isEthereumPresent']);

    console.log(isEthereumPresent());

    onMounted(async () => {
      localState.hasEthereum = await isEthereumPresent();
    });

    return {
      localState,
    };
  },
});
```

Vuex-Module:

```typescript
export const actions: ActionTree<IAuthState, IRootState> = {
  isEthereumPresent(): boolean {
    return !!window.ethereum;
  },
};
```

So as you see, the `isEthereumPresent` is not asynchronous, but calling it from within the Vue-Component returns a promise on the `console.log()` and has to be called with `await`. Is this intended/known?

**Comment by davidmeirlevy** [comment]
We aren't manipulating the return value of vuex.
As far as I know, `$store.dispatch()` method always return a promise.

Try to check it out: 
```
setup(props, {root: {$store}}) {
console.log($store.dispatch('authModule/isEthereumPresent'))
}
```
You will get a promise too, because it's a Vuex behavior. (mentioned here: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/23838#note_278359196)
