### ISSUE TITLE
No branch for supporting Vue 3 / Vuex 4

### ISSUE THREAD

**Issue by iGoog** [greenpress/vuex-composition-helpers#14]
It would be nice to support composition via Vue 3. Imports need to be updated, test-utils package need to be changed out and all the tests updated as well.
```
import {computed} from 'vue';
import {useStore} from 'vuex';
```

**Comment by davidmeirlevy** [comment]
This library was made to help you use the composition API inside vue2, very much like the `@vue/composition-api` library.
The day you'll upgrade to vue 3 + vuex 4, you should gladly remove both of those packages from your package.json.

After a talk to the vuex team few months ago, I tried to PR them with the "useXX" API, and they told me it will be on the next version, so I created this library for now and asked if that is how they intend to implement the new API, and they agreed.
