### ISSUE TITLE
Possible to create typed mapping for namespaced modules?

### ISSUE THREAD

**Issue by Juxsta** [greenpress/vuex-composition-helpers#20]
I'm looking to see if there is a way to use typed mappings with namespaced modules.
It seems that the methods on createNameSpacedHelpers do not take a type argument, although they do when compared to importing directly from the library.
Is this intended or am I missing something?

**Comment by davidmeirlevy** [comment]
The types can be passed at the usage of the `createNamespacedHelpers` itself.

**Comment by Juxsta** [comment]
Ahhh, I missed that. Perhaps that should be in the documentation?

Anyway, this solved my problem.

Cheers!

**Comment by davidmeirlevy** [comment]
Great!

if you are willing to contribute to the docs, It'll be great :)
