### ISSUE TITLE
Getters not working

### ISSUE THREAD

**Issue by grosenberg** [greenpress/vuex-composition-helpers#22]
Action and State helpers appear to work per the documentation, but getters fail with 

`[Vue warn]: Error in v-on handler: "TypeError: isShowing is not a function"`

Question is, what am I doing wrong/misundestanding from the docs?

Details: the SFC is nothing more than a button, with `@click="toggle()` and this script:

```javascript
  import { ref, computed } from '@vue/composition-api';
  import { createNamespacedHelpers } from 'vuex-composition-helpers/dist';
  const { useState, useActions, useGetters } = createNamespacedHelpers('sidebar');
  // import { useState, useGetters, useActions } from 'vuex-composition-helpers/dist';

  export default {
    setup(props, context) {
      const { showing } = useState(['showing']);
      const { isShowing } = useGetters(['isShowing']);
      const { setShowing } = useActions(['setShowing']);

      function toggle() {
        setShowing(!isShowing());  // <-- line where the error occurs
        console.log('app-bar: toggle=' + isShowing());
      }

      return {
        showing,
        isShowing,
        toggle,
      };
    },
  };
```

Using a standard modular store; tested & currently working under Vue 2. Module is 'sidebar.js'

```javascript
const state = {
  showing: false,
};
const getters = {
  isShowing: (state) => {
    console.log('sb: isShowing=' + state.showing);
    return state.showing;
  },
};
const actions = {
  setShowing: ({ commit }, val) => {
    console.log('sb: setShowing=' + state.showing + '->' + val);
    commit('changeShowing', val);
  },
};
const mutations = {
  changeShowing: (state, val) => {
    state.showing = val;
  },
};
export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations,
};

```

**Comment by grosenberg** [comment]
Also seeing this warning.  Not sure if it is related

`npm WARN vuex-composition-helpers@1.0.20 requires a peer of @vue/composition-api@>= 0.4.0 but none is installed. You must install peer dependencies yourself.`

**Comment by davidmeirlevy** [comment]
`isShowing` is really not a function,  it's a `computed`.
If you want to read it. do it with the composition-way: `isShowing.value`.

**Comment by grosenberg** [comment]
Ok, Thanks. 

To be certain, I had expected these two functions to be equivalent:

    const { showing } = useState(['showing']);
    const { isShowing } = useGetter(['isShowing']);

    function toggle() {
        setShowing(!isShowing());
    }
    function toggle() {
        setShowing(!showing.value);
    }

Would make the `helpers` more intuitively helpful.

Again, much thanks.

**Comment by davidmeirlevy** [comment]
The composition API doesn’t expect a function for a better, it expects a computed “hook”.
This library was made to help you work with the composition API, so the getter and the state both returning a “refs” of composition API.

**Comment by marr** [comment]
Sorry to revive an old issue, but can you offer some guidance here?

I am looking for a simpler way to do this:
```
import { createNamespacedHelpers } from 'vuex-composition-helpers'; 

const { useGetters } = createNamespacedHelpers('catalogs')
const { entries, serverItemsLength } = useGetters(['entries', 'serverItemsLength']);
...
<CatalogList :entries="entries" :server-items-length="serverItemsLength" />
```

My store is inside a nuxt module (it's just _stores/catalog.js_) and has simple getters:
```
export const getters = {
  entries: state => state.allCatalogs,
  serverItemsLength: state => state.totalCount
}
```

The values I get back from the namespaced getter call are both refs, so I can't do something like:

```
const catalogs = useGetters(['entries', 'serverItemsLength']);
...
<CatalogList v-bind="catalogs" />
```

Two questions:
1. Do I have to use the `createNamespacedHelpers` function?
2. Is there a way to supply the entire getters object as a prop to my component?

Note I am using Vue 2.7 and Nuxt 2.

Thanks for any help!

**Comment by davidmeirlevy** [comment]
you have a question, not an issue. please please please open this question on StackOverflow and not here. 🙏 .
you can share the link to the question there and I'll try to answer it.

thanks.
