### ISSUE TITLE
Error when type the createNamespacedHelpers's useGetters

### ISSUE THREAD

**Issue by patrickalima98** [greenpress/vuex-composition-helpers#29]
Hello, how are you?

I'm getting an error from Vetux extension, when I try to type my useGetters from the createNamespacedHelpers.

Here is the useGetters type:
```ts
export declare function useGetters<TGetters = any>(storeOrMap: Store<any> | KnownKeys<TGetters>[], map?: KnownKeys<TGetters>[]): ExtractGetterTypes<TGetters>;
```

And here is the createNamespacedHelpers's useGetters:

```ts
export declare function createNamespacedHelpers<TState = any, TGetters = any, TActions = any, TMutations = any>(storeOrNamespace: Store<any> | string, namespace?: string): {
    useState: (map?: KnownKeys<TState>[]) => RefTypes<TState>;
    useGetters: (map?: KnownKeys<TGetters>[]) => ExtractGetterTypes<TGetters>;
    useMutations: (map?: KnownKeys<TMutations>[]) => ExtractTypes<TMutations, Function>;
    useActions: (map?: KnownKeys<TActions>[]) => ExtractTypes<TActions, Function>;
};
```
And the error:
![Screenshot from 2020-10-25 18-13-53](https://user-images.githubusercontent.com/17622137/97119302-06f9e500-16ee-11eb-97f1-36807ea8e1aa.png)

It's impossible type my getters and actions when I use the createNamespacedHelpers, to solve it, I need make this:
```js
const { name } = useGetters(['name']) as unknown as IUserGetters;
```

**Comment by davidmeirlevy** [comment]
Hi,

You need to define the getters types at the usage of "createNamespacedHelpers".
The "useGetters" should be valid afterwards.

**Comment by patrickalima98** [comment]
Hello, You right. You suggestion works very well
