### ISSUE TITLE
Package does not work on a non-Typescript project without manual compile

### ISSUE THREAD

**Issue by Codermar** [greenpress/vuex-composition-helpers#3]
import package out of the box got:

Failed to compile.
./node_modules/vuex-composition-helpers/src/index.ts Module not found: Error: Can’t resolve ‘./global’ in ‘/usr/local/project/honeycomb-admin-tools-prelim/node_modules/vuex-composition-helpers/src’

**Comment by davidmeirlevy** [comment]
you should import directly from `vuex-composition-helpers/dist`.

**Comment by davidmeirlevy** [comment]
The original "src" folder is in TS, and the "dist" folder contains es2019 without any minification or uglification.
What would be the best option for you to use as a JS user?

**Comment by davidmeirlevy** [comment]
I'm closing this issue.
