### ISSUE TITLE
Doesn't work with composition api beta.22

### ISSUE THREAD

**Issue by Landen13** [greenpress/vuex-composition-helpers#34]
`@vue/composition-api` has been updated to beta.22. This version has 1 breaking change, that affects `vuex-composition-helpers` (it stops loading store).

Please, fix.

Breaking changes in beta.22:
https://github.com/vuejs/composition-api/blob/master/CHANGELOG.md#breaking-changes

**Comment by davidmeirlevy** [comment]
Thanks for this issue.
Will be fixed as soon as possible!

**Comment by davidmeirlevy** [comment]
@Landen13 can you please check my PR and see if it works for you? (You can use npm link or direct copy of the build files).

I didn't have the time to setup an environment of the new composition version, so I haven't tested it yet.

**Comment by davidmeirlevy** [comment]
Done.
Fixed on version 1.0.22
