### ISSUE TITLE
Awaiting actions

### ISSUE THREAD

**Issue by kbruskiewicz** [greenpress/vuex-composition-helpers#4]
In certain parts of my application I need to await an dispatched action.

However since in this library, actions are called through a synchronous function, I believe they are no longer awaitable.

Do you feel like it is a coherent change to convert getAction into an async function?

**Comment by davidmeirlevy** [comment]
as long as I know, "getActions" gives you a map to the actual `dispatch`, so if your action returns a promise (or it's an async function), you can still `await` for it.

Please try. if it won't, I'll fix (because it should).
If it works, tell me and I'll close this issue.
