### ISSUE TITLE
[Typescript] [next] UnwrapRef is not taken into consideration when destructuring result from useXXXX

### ISSUE THREAD

**Issue by n-kogo** [greenpress/vuex-composition-helpers#43]
Hello,

It seems like object destructuration is not taken into account correctly when destructuring from useXXX functions, despite being used as examples.

A non nested computed value is unwrapped with the type `Ref<UnwrapRef<T>>`. 
https://v3.vuejs.org/guide/reactivity-fundamentals.html#ref-unwrapping

Here is an example:

```ts
setup() {
   const {count} = useState(['count']);

  return {
     count
  }
},
methods: {
    increment: function() {
      this.count.value++; //valid at compile time, but has runtime error
      this.count++; //doesn't compile, but correctly runs
   }
}
```

This is really bothersome, as I'm forced to not use destructuration, and go like this: `this.rootState.count.value`, which is so much longer than `this.count`

**Comment by davidmeirlevy** [comment]
If you're using vue3, you need to install "vuex-composition-helpers@next".
Have you?

**Comment by n-kogo** [comment]
I have, yes, package.json line is:
```
    "vuex-composition-helpers": "^2.0.0"
```

Maybe my issue comes from an incomplete configuration ? I'm using vue-cli, and have configured it this way:

```js
///vue.config.js
module.exports = {
  transpileDependencies: ['vuex-composition-helpers'],
}
```
It works fine though, so that may no be it.
The documented configuration provided in the readme didn't work for me:

```ts
// vue.config.js
module.exports = {
  ...
  chainWebpack: config => {
    config
      .rule('ts')
      .include
      .add(/vuex-composition-helpers/)
  }
}
```

**Comment by davidmeirlevy** [comment]
Do you use TS in your project?

**Comment by n-kogo** [comment]
I do, that's why I have the issue in the first place.

If you have a working example of a destructured return from useXXXX working as an UnwrapRef, I could maybe figure out the differences with my setup.

My real use case looks something like that:
```ts
setup() {
    const {player_nickname} = useState<RootStateData>(['player_nickname']);
    
    return {
       player_nickname
    }
},
methods: {
    join() {
        if (this.player_nickname.length > 3) { // doesn't compile
            //...
        }
    }
}
```

The installed dependencies from my package.json, if that can help you: 
```json
{
  "dependencies": {
    "socket.io-client": "^4.0.0",
    "vue": "^3.0.0",
    "vue-class-component": "^7.2.6",
    "vue-router": "^4.0.5",
    "vue-socket.io-extended": "^5.0.0-alpha.4",
    "vuex": "^4.0.0",
    "vuex-composition-helpers": "^2.0.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "^4.5.12",
    "@vue/cli-plugin-typescript": "^4.5.12",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/runtime-core": "^3.0.11",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "sass": "^1.32.12",
    "sass-loader": "^10",
    "typescript": "~4.1.5"
  }
}
```

**Comment by davidmeirlevy** [comment]
Why do you use both options api and composition api?

**Comment by n-kogo** [comment]
Because both are available at the same time in Vue3, and I prefer the separating data setup and method definition in two separate sections, it's not an issue per se, and works fine for all other use cases.

And the issue would remain the same if I use a full composition API schema, and try to use the values in templates, the intellisense gets confused in the same way. 

I don't see any mention of UnwrapRef anywhere in the vuex-composition-helpers, unlike the official lib which separates ref return type depending on the type of the value provided:

```ts
//@vue/reactivity/dist/reactivity.d.ts
export declare function ref<T extends object>(value: T): ToRef<T>;

export declare function ref<T>(value: T): Ref<UnwrapRef<T>>;
```

I understand setting up such a condition is quite a bit harder for `RefTypes` and the like, but unless I'm mistaken, it seems like this is something lacking from the lib right now.

**Comment by n-kogo** [comment]
I ended up going for something dirty, wrapping useXXX calls with a custom function to convert the type when I use destructuration: 
```ts
export type  UnwrappedRefTypes<Type> = {
    [Key in keyof Type] :Ref<UnwrapRef<Type[Key]>>
}

export function mapUnwrapStates<Type>(refTypes: RefTypes<Type>): UnwrappedRefTypes<Type> {
    return refTypes as unknown as UnwrappedRefTypes<Type>;
}
```

Used as 

```ts
const {player_nickname} = mapUnwrapStates(useState<RootStateData>(['player_nickname']));
```

The issue is still there in the lib, but it doesn't seem I'm conveying it to you correctly, so I'm closing the issue.
