### ISSUE TITLE
[Feature Request] In-place namespaces

### ISSUE THREAD

**Issue by nolde** [greenpress/vuex-composition-helpers#57]
Would be nice to have "in-place" namespaces, similar to what happens with [`vuex` mappers](https://vuex.vuejs.org/api/#component-binding-helpers).

```javascript
import { useGetters } from 'vuex-composition-helpers'

export default {
  setup() {
    const { one, two } = useGetters('my/long/name/space', ['one', 'two'])
    const { uno, dos } = useGetters('my/other/thing', ['uno', 'dos'])
    return { one, two, uno, dos }
  }
}
```

**Comment by davidmeirlevy** [comment]
@nolde as you can see in the source code, the global functions are passing `null` as a namespace to the `useMapping` function.

If you like to create an improvement that will pass the namespace to the global functions, you're welcome, just make sure all the tests will pass :)
