### ISSUE TITLE
mapState returns type any for the computed state

### ISSUE THREAD

**Issue by kpguru20001** [greenpress/vuex-composition-helpers#59]
using mapState returns the following:
<img width="571" alt="Screenshot 2022-01-27 at 9 47 58 AM" src="https://user-images.githubusercontent.com/32976334/151292054-d995f9b0-12ca-4bdc-a6be-dca92a6a1154.png">

what is the right way of defining mapState or any other map in Typescript

**Comment by davidmeirlevy** [comment]
This library handles composition API usage, through "useState" and the setup function, and it doesn't seem that you do that, or even use this library.

The "mapState" is a method under "vuex" itself.
