### ISSUE TITLE
Allow a type interface on using methods

### ISSUE THREAD

**Issue by Stoom** [greenpress/vuex-composition-helpers#6]
Just wanted to make a suggestion to allow for adding a typed interface to provide full typing for the use functions.  I have things split out into an interface for actions, mutations, getters, and state of each module, but almost all of the Vuex Composition APIs drop typing and either emit `Function` or `any` despite the fact that I have fully typed interfaces for all of this.

**Comment by davidmeirlevy** [comment]
Hi :)

Can you share an example?

**Comment by Stoom** [comment]
Sure.  I've also been working on what the types would look like... I'm getting close with something like below.  It's working fairly good with the getters, I'm having a little trouble with actions when they're using an action tree.  If it's an interface that does not inherit from `ActionTree` then it seems to work fine. 🤔 

```ts
import { createNamespacedHelpers as createNsHelper } from 'vuex-composition-helpers';

declare type OmitSingleArgs<F> =
F extends (x: any) => any
  ? ReturnType<F>
  : F;

declare type OmitFirstArg<F, TReturn> =
F extends (x: any, ...args: infer P) => any
  ? (...args: P) => TReturn
  : never;

declare type InferType<T> =
T extends null
  ? any
  : T extends (x: any) => any
    ? OmitSingleArgs<T>
    : T extends (...args: any) => any
      ? OmitFirstArg<T, ReturnType<T>>
      : T;

declare type ExtractTypes<O> = {
  readonly [K in keyof O]: InferType<O[K]>;
};

export const createNamespacedHelpers = <
  TState,
  TGetters,
  TActions,
  TMutations,
>(namespace: string): {
  useState: <TStateKeys extends keyof TState>(...map: TStateKeys[]) => TState;
  useMutations: <TMutationKeys extends keyof TMutations>(...map: TMutationKeys[]) => ExtractTypes<TMutations>;
  useActions: <TActionKeys extends keyof TActions>(...map: TActionKeys[]) => ExtractTypes<TActions>;
  useGetters: <TGetterKeys extends keyof TGetters>(...map: TGetterKeys[]) => ExtractTypes<TGetters>;
} => {
  const module = createNsHelper(namespace);

  return {
    useState: (...map) => module.useState(map as string[]) as TState,
    useMutations: (...map) => module.useMutations(map as string[]) as ExtractTypes<TMutations>,
    useActions: (...map) => module.useActions(map as string[]) as ExtractTypes<TActions>,
    useGetters: (...map) => module.useGetters(map as string[]) as ExtractTypes<TGetters>,
  };
};
```

*Actions*
```ts
export interface ProfileActions extends ActionTree<UserState, RootState> {
  fetchUser(ctx: ActionContext<UserState, RootState>): any;
  fetchByUserId(ctx: ActionContext<UserState, RootState>, payload: number): any;
}
```

*Getters*
```ts
export interface ProfileGetters extends GetterTree<ProfileState, RootState> {
  name(state: ProfileState): string | undefined;
}
```

*Mutations*
```ts
export interface ProfileMutations extends MutationTree<ProfileState> {
  profileLoaded(state: ProfileState, payload?: User): void;
  profileError(state: ProfileState): void;
}
```

*State*
```ts
export interface ProfileState {
  user?: User;
}
```

**Comment by davidmeirlevy** [comment]
If you add a PR of the ability to mention the interface of the helpers, I'll merge it.

Of course, I can make it myself and it will take a few days, maybe even less, but it seems like you already know what you want, and it doesn't interfere with other users, probably even benefits them.

Just don't break the tests :)

**Comment by Stoom** [comment]
Will do 🙂 I don't really know how to test this though since it will be a typescript compilation error

**Comment by davidmeirlevy** [comment]
So if you break it, it won’t pass the jest tests we already have..

**Comment by davidmeirlevy** [comment]
Thanks for the commit. version 1.0.14 includes your code.

**Comment by riddla** [comment]
@Stoom: I'm having trouble getting the types to work in the context of "Namespaced Usage Examples".

```
const { useGetters } = createNamespacedHelpers<IProjectsState, foo>('projects')

const { projects, currentProject } = useGetters([
  'projects',
  'currentProject',
])

// "projects" is now of type "Ref<any>"
```

Can you give me a hint how to keep the types when using the namespaced helpers?

**Comment by Stoom** [comment]
@riddla what does `foo` look like?  Everything looks fine, so maybe it's the order of the types in `createNamespacedHelper`

**Comment by riddla** [comment]
I added the „foo“ definition right to the top of my code snippet.

**Comment by Stoom** [comment]
> I added the „foo“ definition right to the top of my code snippet. 

Aaah so you n Ed to define an interface otherwise it has no clue what your trying to do.  If you look at the `GetterTree` it's just a dictionary with string keys.

**Comment by riddla** [comment]
Thanks for the heads up, @Stoom.
I tried the following (but without luck):

```javascript
export interface ProjectGetters extends GetterTree<IProjectsState, IRootState> {
  projects: Getter<IProjectsState, IRootState>
  currentProject: Getter<IProjectsState, IRootState>
}
```

Did you mean it like that?

**Comment by Stoom** [comment]
@riddla not quite.  There are examples above for each type, and some tests you can look at.

**Comment by Stoom** [comment]
There are also examples in the readme
