### ISSUE TITLE
Error: You must use this function within the "setup()" method, or insert the store as first argument.

### ISSUE THREAD

**Issue by flrnt** [greenpress/vuex-composition-helpers#65]
Hi,
I'm facing the following errors (both related) : 

![image](https://user-images.githubusercontent.com/12048786/163370451-60c6d34b-3a2c-4a01-a586-b58a5f3ae7ea.png)

![image](https://user-images.githubusercontent.com/12048786/163370777-a357a996-a32a-452e-b8b0-f74f06a4fb26.png)

Those errors happen when I wrap useProfile composable into watchEffect composition helper. As long as I don't wrap it, I don't have any error.

NOK
```js
// @/components/UserProfile.vue

<script>
import { ref, watchEffect } from '@vue/composition-api'
import useProfile from '@/composables/useProfile'

export default {
  name: 'UserProfile',
  setup() {
    const name = ref('')

    watchEffect(() => {
      const { fullName } = useProfile()
      name.value = fullName.value
    })

    return {
      name,
    }
  },
}
</script>
```

```js
// @/composables/useProfile.js

import { ref } from '@vue/composition-api'
import { useGetters } from 'vuex-composition-helpers/dist'

export default function useProfile() {
  const { current } = useGetters('users', ['current'])
  const fullName = ref('')

  const { fname, lname } = current.value
  // do something
  fullName.value = `${fname} ${lname}`

  return {
    fullName,
  }
}

```

I reproduce it with dumb component/composable but with exact versions I use in my package.json for current project.  

    "@vue/composition-api": "^1.4.9",
    "vue": "^2.6.11",
    "vuex-composition-helpers": "^1.1.0"

reproduce link : https://codesandbox.io/s/epic-feather-oyg6gt?file=/src/components/UserProfile.vue

**Comment by davidmeirlevy** [comment]
The error is quite clear.

The composition hook must run under the setup function.
You're running it inside a watch callback.

**Comment by flrnt** [comment]
it also throw this error in any function I can write inside the setup function, or in any hook, like onmounted(). You mean that we're not able to run any composable into hooks or fn ? I don't think so.
