### ISSUE TITLE
Vue 2.6 support

### ISSUE THREAD

**Issue by mokone91** [greenpress/vuex-composition-helpers#73]
Hi! version 1.1.1 is not working with vue 2.6 because of 
`
import { computed, getCurrentInstance } from 'vue';
`
This functionality appears from 2.7..
Maybe it is possible to use vue-demi under the hood? this package has 3 positions, so ypu can import  computed and getCurrentInstance from vue-demi, and it will proxy correct instances depends on installed vue version

**Comment by davidmeirlevy** [comment]
oh, huge mistake!
published 1.1.2

thanks!
