### ISSUE TITLE
A problem occurred in v-for.

### ISSUE THREAD

**Issue by SungGyunKim** [greenpress/vuex-composition-helpers#76]
hi.

In the composition API of vue, there is no helper method of vuex, so while searching, I found your library and found an error in the following situation.

I was able to get a ComputedRefImpl object by receiving useState() from createNamespacedHelpers().
ComputedRefImpl object was bidding to <template> and it was confirmed that it was displayed on the screen.
However, the following error occurred with the v-for directive.
For reference, the state being handled is an array.

And you can see that the ComputedRefImpl object obtained through computed() and the ComputedRefImpl obtained through your library are slightly different.

I would like to use your library and hope that that problem is solved.

![1](https://user-images.githubusercontent.com/18004447/193402586-e6bf3518-3ae2-4dcf-8eff-9b9536b91158.png)
![2](https://user-images.githubusercontent.com/18004447/193402593-1ef22e92-fe99-4fa7-9d32-ae33ecf586ee.png)
![화면 캡처 2022-10-01 182129](https://user-images.githubusercontent.com/18004447/193402595-d1c89830-7f85-46fa-8cc6-35b4d21994bc.png)
![화면 캡처 2022-10-01 182147](https://user-images.githubusercontent.com/18004447/193402604-83ff9bac-61bd-43ca-979c-5f20c863ff06.png)

**Comment by davidmeirlevy** [comment]
I don't think you can use the "createNamespacedHelpers" before the store was initiated and defined.

**Comment by SungGyunKim** [comment]
As I said, even if you call createNamespacedHelpers() when using the Store, the same symptoms are present.

![화면 캡처 2022-10-02 142401](https://user-images.githubusercontent.com/18004447/193439316-e4fe37ec-62e8-40d9-8d6e-ea61133c795b.png)

**Comment by SungGyunKim** [comment]
My repository is below.
Can you help?

https://github.com/SungGyunKim/vue3-guide-project.git

**Comment by SungGyunKim** [comment]
Your help was great in solving it.
Thank you very much.

**Comment by davidmeirlevy** [comment]
you're welcome :)
